[package]
name = "singles-in-your-area"
version = "0.3.3"
authors = ["Michael Ripley <zkxs00@gmail.com>"]
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
tokio = { version = "1", features = ["full"] }
warp = "0.3" # uses tokio 1.0
chrono = "0.4"
image = "0.24"
imageproc = "0.23"
rusttype = "0.9"
maxminddb = "0.23"
lazy_static = "1"
serde = { version = "1", features = ["derive"] }
toml = "0.8"
const_format = "^0.2"
