[package]
name = "singles-in-your-area"
version = "0.3.2"
authors = ["Michael Ripley <zkxs00@gmail.com>"]
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
tokio = { version = "^1.1.0", features = ["full"] }
warp = "^0.3.0" # uses tokio 1.0
chrono = "^0.4.0"
image = "^0.24.3"
imageproc = "^0.23.0"
rusttype = "^0.9.2"
maxminddb = "^0.23.0"
lazy_static = "^1.4.0"
serde = { version = "^1.0.150", features = ["derive"] }
toml = "^0.5.8"
const_format = "^0.2.26"
